// Common Icons you use in Every App

const FeatherIcons = {
  home: "home",
  menu: "menu",
  radioOff: "circle",
  radioOn: "check-circle",
  translate: "globe",
  mobile: "smartphone",
  lock: "lock",
  unLock: "unlock",
  eyeOn: "eye",
  eyeOff: "eye-off",
  user: "user",
  mail: "mail",
  backL: "chevron-left",
  backR: "chevron-right",
  arrowUp: "chevron-up",
  arrowDown: "chevron-down",
  arrowRight: "chevron-right",
  arrowLeft: "chevron-left",
  cart: "shopping-cart",
  categories: "figma",
  plus: "plus",
  plusCircle: "plus-circle",
  minus: "minus",
  minusCircle: "minus-circle",
  delete: "trash-2",
  unCheck: "square",
  check: "check-square",
  calendar: "calendar",
  price: "dollar-sign",
  close: "x",
  map: "map-pin",
  grid: "grid",
  list: "list",
  logOut: "log-out",
  filter: "filter",
  true: "check",
  credit: "credit-card",
  clock: "clock",
  call: "phone-call",
  archive: "archive",
  edit: "edit-2",
  clipboard: "clipboard",
  award: "award",
  alert: "alert-circle",
  toggleOff: "toggle-left",
  toggleOn: "toggle-right",
  notification: "bell",
  sort: "bar-chart-2",
  send: "send",
  checkOnly: "check",
  search: "search",
  chat: "message-square",
  chatCircle: "message-circle",
  share: "share-2",
  fast: "rewind",
  play: "play",
  playCircel: "play-circle",
  pause: "pause",
  pauseCircle: "pause-circle",
  moreH: "more-horizontal",
  mic: "mic",
  image: "image",
  camera: "camera",
  cartBag: "shopping-bag",
  offer: "tag",
  moreVerical: "more-vertical",
  truck: "truck",
  gift: "gift",
  upload: "upload-cloud",
  circle: "aperture",
  layers: "layers",
  framer: "framer",
  star: "star",
  heart: "heart",
};

const Fontisto = {
  cart: "shopping-basket",
  cartRemove: "shopping-basket-remove",
  cartAdd: "shopping-basket-add",
  heartSolid: "heart",
  heartEmpty: "heart-alt",
  // Social Media
  whatsApp: "whatsapp",
  compass: "compass-alt",
  wallet: "wallet",
  card: "credit-card",
  walletGoogle: "google-wallet",
  google: "google",
  facebook: "facebook",
  twitter: "twitter",
  setting: "player-settings",
  notification: "bell-alt",
  money: "money-symbol",
  heart: "heart",
  upload: "cloud-up",
  email: "email",
  call: "call",
  users: "persons",
  yelp: "yelp",
  share: "share",
  world: "world",
};

const FontAwesomeIcons = {
  up: "sort-up",
  down: "sort-down",
};

const Ionicons = {
  camera: "ios-camera",
  upload: "cloud-upload-outline",
  //
  Menu: "ios-menu",
  Home: "ios-home",
  HomeOutline: "ios-home",
  Back: "ios-arrow-back",
  Forward: "ios-arrow-forward",
  Config: "ios-settings",
  More: "ios-more",
  SignIn: "ios-log-in",
  SignOut: "ios-log-out",
  ShoppingCart: "ios-cart",
  ShoppingCartEmpty: "ios-cart",
  Sort: "ios-funnel",
  Filter: "ios-funnel",
  ShowItem: "ios-arrow-dropright",
  HideItem: "ios-arrow-dropup",
  ListMode: "ios-list-box",
  GridMode: "ios-grid",
  Star: "ios-star",
  StarOutline: "ios-star",
  Wishlist: "ios-heart",
  WishlistEmpty: "ios-heart",
  Delete: "ios-trash",
  AddToCart: "ios-cart",
  MyOrder: "ios-cube",
  News: "ios-paper",
  Mail: "ios-mail",
  RatioOff: "ios-radio-button-off",
  RatioOn: "ios-radio-button-on",
  Search: "ios-search",
  Close: "ios-close",
  HappyFace: "ios-happy",
  SadFace: "ios-sad",
  ChatBubble: "ios-chatbubbles",
  ChatBubbleOutline: "ios-chatbubbles",
  Information: "ios-information",
  Person: "ios-person",
  PersonOutline: "ios-person",
  DropDown: "md-arrow-dropdown",
  Facebook: "logo-facebook",
  Google: "logo-google",
  Notifications: "ios-notifications",
  Camera: "logo-instagram",
  Contact: "ios-contact",
  Email: "md-mail",
  Lock: "md-lock",
  CheckCircle: "ios-checkmark-circle",
  RemoveCircle: "ios-remove-circle",
  PriceTags: "ios-pricetags",
  CheckMark: "ios-checkmark",
  Contact: "ios-contact",
  Categories: "md-options",
  Forward: "ios-arrow-forward",
  Down: "ios-arrow-down",
  Add: "ios-add",
  Remove: "ios-remove",
  Categories: "md-options",
  DownArrow: "md-arrow-dropdown",
  RightArrow: "md-arrow-dropright",
  image: "image-outline",
};

export { FeatherIcons, Fontisto, Ionicons, FontAwesomeIcons };
